version: '3.8'

services:
  llvm13:
    container_name: MetaCompiler_container
    image: meta_compiler
    build: .
    hostname: OwO
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
